/* Generated By:JavaCC: Do not edit this line. LOGOConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LOGOConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORWARD = 5;
  /** RegularExpression Id. */
  int FD = 6;
  /** RegularExpression Id. */
  int RIGHT = 7;
  /** RegularExpression Id. */
  int RT = 8;
  /** RegularExpression Id. */
  int LEFT = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int REPEAT = 11;
  /** RegularExpression Id. */
  int PENUP = 12;
  /** RegularExpression Id. */
  int PENDOWN = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;
  /** RegularExpression Id. */
  int PERIOD = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int LB = 17;
  /** RegularExpression Id. */
  int RB = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"FORWARD\"",
    "\"FD\"",
    "\"RIGHT\"",
    "\"RT\"",
    "\"LEFT\"",
    "\"LT\"",
    "\"REPEAT\"",
    "\"PENUP\"",
    "\"PENDOWN\"",
    "<CONSTANT>",
    "\".\"",
    "<DIGIT>",
    "\"[\"",
    "\"]\"",
  };

}
